version: "3.4"
services:
  fusionauth:
    container_name: fusionauth
    image: fusionauth/fusionauth-app:latest

  search:
    container_name: fusionauth.search
    image: opensearchproject/opensearch:2.11.0

  db:
    container_name: fusionauth.db
    image: postgres:16.0-bookworm

  redis:
    container_name: redis
    image: redis

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine

  tinder.api:
    container_name: tinder.api
    image: ${DOCKER_REGISTRY-}tinderapi
    build:
      context: .
      dockerfile: Tinder/Tinder.API/Dockerfile

  tinder.mssqldb:
    container_name: tinder.mssqldb
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"

  subscription.service:
    container_name: subscription.service
    image: ${DOCKER_REGISTRY-}subscription.service
    build:
      context: .
      dockerfile: SubscriptionService/SubscriptionService.API/Dockerfile

  mongodb_container:
    container_name: subscription.service.mongodb
    image: mongo:latest

  notification.service:
    container_name: notification.service
    image: ${DOCKER_REGISTRY-}notification.service
    build:
      context: .
      dockerfile: NotificationService/NotificationService.API/Dockerfile

  graphql:
    container_name: graphql.service
    image: ${DOCKER_REGISTRY-}graphql
    build:
      context: .
      dockerfile: GraphQlService/GraphQlService/Dockerfile