apiVersion: v1
kind: Service
metadata:
  name: graphqlpservice-srv
spec:
  type: NodePort
  selector:
    app: graphqlservice
  ports:
    - name: graphqlservice
      protocol: TCP
      port: 80
      targetPort: 5004
