apiVersion: v1
kind: Service
metadata:
  name: subscriptionnpservice-srv
spec:
  type: NodePort
  selector:
    app: subscriptionservice
  ports:
    - name: subscriptionservice
      protocol: TCP
      port: 80
      targetPort: 5002
